Adding status to freeswitch script

diff --git a/init.d/freeswitch b/init.d/freeswitch
--- a/init.d/freeswitch
+++ b/init.d/freeswitch
@@ -57,9 +57,9 @@ do_start()
         #   0 if daemon has been started
         #   1 if daemon was already running
         #   2 if daemon could not be started
-        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null -- \
+        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null 2>&1 -- \
                 || return 1
-        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
+        start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON > /dev/null 2>&1 -- \
                 $DAEMON_ARGS \
                 || return 2
         # Add code here, if necessary, that waits for the process to be ready
@@ -132,6 +132,17 @@ case "$1" in
         #do_reload
         #log_end_msg $?
         #;;
+
+  status)
+        [ -f "$PIDFILE" ] && PROCESS="$(cat $PIDFILE)" || PROCESS=''
+        if [ -n "$PROCESS" ] ; then
+        log_success_msg "freeswitch with pid $PROCESS is running."
+        	exit 0
+      	else
+        log_warning_msg "Could not find freeswitch running."
+        	 exit 1
+      	fi
+      	;;
   restart|force-reload)
         #
         # If the "reload" option is implemented then remove the
